---
# Tasks for installing and configuring LogWatch


- name: install LogWatch
  ansible.builtin.package:
    name: logwatch
    state: present
    update_cache: yes
  become: yes

- name: configure LogWatch
  ansible.builtin.template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: "{{ logwatch_admin_group }}"
    mode: 0664
  become: yes


# Schedule LogWatch to run

# - name: remove improperly named cron script
#   ansible.builtin.file:
#     path: /etc/cron.daily/0logwatch
#     state: absent
#   become: yes

# - name: schedule the cron job
#   ansible.builtin.template:
#     src: 00logwatch.j2
#     dest: /etc/cron.daily/00logwatch
#     owner: root
#     group: "{{ logwatch_admin_group }}"
#     mode: 0775
#   become: yes


# Add/configure Apt package update checks

- name: add Apt packages to update check
  ansible.builtin.copy:
    src: updates
    dest: /usr/share/logwatch/scripts/services/updates
    owner: root
    group: root
    mode: 0755
  become: yes
  when: "ansible_os_family == 'Debian' and logwatch_updates_check|bool"

- name: configure Apt packages to update check
  ansible.builtin.template:
    src: updates.conf.j2
    dest: /etc/logwatch/conf/services/updates.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when: "ansible_os_family == 'Debian' and logwatch_updates_check|bool"
